### ISSUE TITLE
Your email regex is sadly very wrong.

### ISSUE THREAD

**Issue by RandalSchwartz** [rifqempul/string_utility#1]
Please use https://pub.dev/packages/email_validator instead.

**Comment by rifkyputra** [comment]
what are use cases you're trying to achieve ? can you show me some example ?

you can try test cases in `test/extensions_test.dart` .

**Comment by RandalSchwartz** [comment]
For
```
        return this.contains(
          RegExp(r'^([a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6})*$'));
```

You are permitting `a..b@example.com` which is illegal.  But you are omitting an entire set of addresses.  For example, the quite commonly used "plus" addressing: `realmerlyn+test@gmail.com`.  But also real working addresses like `fred&barney@stonehenge.com` (it's an autoresponder... try it!) and `*@qz.to` (who has since changed to `*@his.domain.org`.

Please don't check for only things you've seen.  Maybe you haven't seen the full power of RFC822.  `email_validator` gets it right.
